In [1]:
import yfinance as yf

In [3]:
msft = yf.Ticker("MSFT")

display(msft.info)

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "Microsoft Corporation, a technology company, develops and supports a portfolio of technology solutions for individuals and businesses worldwide. Its products include operating systems, server applications, business solution applications, software development tools, desktop and server management tools, and video games; and devices, such as PCs, tablets, gaming and entertainment consoles, other intelligent devices, and related accessories. The company's Productivity and Business Processes segment offers Microsoft 365 Commercial, Enterprise Mobility + Security, Power BI, Exchange, SharePoint, Microsoft Teams, Microsoft 365 Security and Compliance, Microsoft 365 Copilot, and Windows Commercial on-premises and Office licensed on-premises. This segment also provides Microsoft 365 Consumer products and cloud services; LinkedIn, including talent solutions, marketing solutions, subscriptions, and sales solutions; Dynamics 365, a set of cloud-based applications; and on-premises ERP and CRM applications. Its Intelligent Cloud segment offers server products and cloud services; cloud and AI consumption-based services, GitHub cloud services, health and life sciences cloud services, as well as virtual desktop offerings, and other cloud services; SQL Server, Windows Server, Visual Studio, System Center, and related client access licenses; and enterprise support services, industry solutions, Microsoft partner network, and learning experience. The company's More Personal Computing segment provides Windows OEM licensing and devices comprising Surface and PC accessories; XBOX hardware, and XBOX first- and third-party content and services; XBOX Game Pass and other subscriptions; XBOX Cloud Gaming, advertising, and other cloud services; and search advertising consisting of Bing, Copilot, Microsoft News, Microsoft Edge, and third-party affiliates. It sells its products through partners and retail networks. The company was founded in 1975 and is headquartered in Redmond, Washington.",
 'fullTimeEmployees': 223000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 54,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 52,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1973,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 7,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1785542400,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 505.06,
 'open': 505.33,
 'dayLow': 504.8675,
 'dayHigh': 517.78,
 'regularMarketPreviousClose': 505.06,
 'regularMarketOpen': 505.33,
 'regularMarketDayLow': 504.8675,
 'regularMarketDayHigh': 517.78,
 'dividendRate': 3.64,
 'dividendYield': 0.71,
 'exDividendDate': 1787184000,
 'payoutRatio': 0.1983,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.099,
 'trailingPE': 28.169502,
 'forwardPE': 21.78441,
 'volume': 28953449,
 'regularMarketVolume': 28953449,
 'averageVolume': 38141796,
 'averageVolume10days': 23159270,
 'averageDailyVolume10Day': 23159270,
 'bid': 510.7,
 'ask': 519.98,
 'bidSize': 1,
 'askSize': 4,
 'marketCap': 3813240733696,
 'nonDilutedMarketCap': 3750346005684,
 'fiftyTwoWeekLow': 349.2,
 'fiftyTwoWeekHigh': 553.72,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'fulldayPrice': 513.06,
 'fulldayChange': 8.47003,
 'fulldayChangePercent': 1.67703,
 'priceToSalesTrailing12Months': 11.491237,
 'fiftyDayAverage': 430.6526,
 'twoHundredDayAverage': 431.17566,
 'trailingAnnualDividendRate': 3.64,
 'trailingAnnualDividendYield': 0.007207065,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3865210257408,
 'profitMargins': 0.40305,
 'floatShares': 7414481428,
 'sharesOutstanding': 7425545491,
 'sharesShort': 68544953,
 'sharesShortPriorMonth': 92373474,
 'sharesShortPreviousMonthDate': 1784073600,
 'dateShortInterest': 1786665600,
 'sharesPercentSharesOut': 0.0092,
 'heldPercentInsiders': 0.00090000004,
 'heldPercentInstitutions': 0.75882006,
 'shortRatio': 1.85,
 'shortPercentOfFloat': 0.0092,
 'impliedSharesOutstanding': 7425545491,
 'bookValue': 59.565,
 'priceToBook': 8.621339,
 'lastFiscalYearEnd': 1782777600,
 'nextFiscalYearEnd': 1814313600,
 'mostRecentQuarter': 1782777600,
 'earningsQuarterlyGrowth': 0.313,
 'netIncomeToCommon': 133748998144,
 'trailingEps': 18.23,
 'forwardEps': 23.57328,
 'pegRatio': 1.64,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 11.648,
 'enterpriseToEbitda': 19.899,
 '52WeekChange': 0.016649485,
 'SandP52WeekChange': 0.20204377,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1787184000,
 'quoteType': 'EQUITY',
 'currentPrice': 513.53,
 'targetHighPrice': 870.0,
 'targetLowPrice': 400.0,
 'targetMeanPrice': 569.4537,
 'targetMedianPrice': 550.0,
 'recommendationMean': 1.36364,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 52,
 'totalCash': 76842999808,
 'totalCashPerShare': 10.348,
 'ebitda': 194237005824,
 'totalDebt': 128812998656,
 'quickRatio': 1.099,
 'currentRatio': 1.23,
 'totalRevenue': 331839012864,
 'debtToEquity': 29.118,
 'revenuePerShare': 44.668,
 'returnOnAssets': 0.14088,
 'returnOnEquity': 0.34039003,
 'grossProfits': 225465008128,
 'freeCashflow': 16545500160,
 'operatingCashflow': 182934994944,
 'earningsGrowth': 0.317,
 'revenueGrowth': 0.177,
 'grossMargins': 0.67944,
 'ebitdaMargins': 0.58534,
 'operatingMargins': 0.45111,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'postMarketChangePercent': -0.091529556,
 'postMarketPrice': 513.06,
 'postMarketChange': -0.47003174,
 'regularMarketChange': 8.47003,
 'regularMarketDayRange': '504.8675 - 517.78',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 38141796,
 'fiftyTwoWeekLowChange': 164.33002,
 'fiftyTwoWeekLowChangePercent': 0.47058997,
 'fiftyTwoWeekRange': '349.2 - 553.72',
 'fiftyTwoWeekHighChange': -40.18994,
 'fiftyTwoWeekHighChangePercent': -0.07258171,
 'fiftyTwoWeekChangePercent': 1.6649485,
 'dividendDate': 1788998400,
 'earningsTimestamp': 1785355200,
 'earningsTimestampStart': 1793217600,
 'earningsTimestampEnd': 1793217600,
 'earningsCallTimestampStart': 1785360600,
 'earningsCallTimestampEnd': 1785360600,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 18.23,
 'epsForward': 23.57328,
 'epsCurrentYear': 19.75306,
 'priceEpsCurrentYear': 25.997494,
 'fiftyDayAverageChange': 82.87744,
 'fiftyDayAverageChangePercent': 0.19244617,
 'twoHundredDayAverageChange': 82.35437,
 'twoHundredDayAverageChangePercent': 0.19099958,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.4 - Strong Buy',
 'cryptoTradeable': False,
 'regularMarketChangePercent': 1.67703,
 'regularMarketPrice': 513.53,
 'corporateActions': [],
 'postMarketTime': 1787961586,
 'regularMarketTime': 1787947201,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.6402}

In [5]:
hist = msft.history(period="5d")
display(hist)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-08-24 00:00:00-04:00,483.209991,490.609985,481.859985,487.309998,17230800,0.0,0.0
2026-08-25 00:00:00-04:00,485.440002,492.440002,484.299988,491.709991,19519000,0.0,0.0
2026-08-26 00:00:00-04:00,487.850006,497.399994,487.309998,496.369995,20758900,0.0,0.0
2026-08-27 00:00:00-04:00,494.880005,506.480011,490.079987,505.059998,28688800,0.0,0.0
2026-08-28 00:00:00-04:00,NaN,NaN,NaN,NaN,28953449,0.0,0.0

In [7]:
msft.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m         14   38     3     0           0
1    -1m         14   40     3     0           0
2    -2m         13   41     3     0           0
3    -3m         12   41     3     0           0

In [8]:
pltr = yf.Ticker("PLTR")
hist2 = pltr.history(period="5d")
display(hist2)
pltr.recommendations

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-08-24 00:00:00-04:00,177.389999,178.750000,171.309998,175.889999,35115500,0.0,0.0
2026-08-25 00:00:00-04:00,176.630005,179.869995,172.199997,172.729996,24558500,0.0,0.0
2026-08-26 00:00:00-04:00,170.600006,178.490005,168.899994,177.500000,27924200,0.0,0.0
2026-08-27 00:00:00-04:00,178.750000,186.860001,178.009995,185.929993,40739300,0.0,0.0
2026-08-28 00:00:00-04:00,NaN,NaN,NaN,NaN,24959261,0.0,0.0

  period  strongBuy  buy  hold  sell  strongSell
0     0m          1   20     9     1           1
1    -1m          1   19    10     1           1
2    -2m          2   18    10     1           1
3    -3m          1   18    10     1           1

In [4]:
from gpt_functions import get_yf_stock_info

info = get_yf_stock_info('AAPL')

{'address1': 'One Apple Park Way', 'city': 'Cupertino', 'state': 'CA', 'zip': '95014', 'country': 'United States', 'phone': '(408) 996-1010', 'website': 'https://www.apple.com', 'industry': 'Consumer Electronics', 'industryKey': 'consumer-electronics', 'industryDisp': 'Consumer Electronics', 'sector': 'Technology', 'sectorKey': 'technology', 'sectorDisp': 'Technology', 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allows customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.', 'fullTimeEmployees': 150000, 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Timothy D. Cook', 'age': 64, 'title': 'CEO & Director', 'yearBorn': 1961, 'fiscalYear': 2025, 'totalPay': 16759518, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Kevan  Parekh', 'age': 53, 'title': 'Senior VP & CFO', 'yearBorn': 1972, 'fiscalYear': 2025, 'totalPay': 4034174, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Sabih  Khan', 'age': 58, 'title': 'Senior VP & Chief Operating Officer', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5021905, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': "Ms. Deirdre  O'Brien", 'age': 58, 'title': 'Senior Vice President of Retail & People', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5037867, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Katherine L. Adams', 'age': 61, 'title': 'Senior VP of Government Affairs & Secretary', 'yearBorn': 1964, 'fiscalYear': 2025, 'totalPay': 5022482, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Ben  Borders', 'age': 44, 'title': 'Principal Accounting Officer', 'yearBorn': 1981, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Suhasini  Chandramouli', 'title': 'Director of Investor Relations', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Jennifer G. Newstead J.D.', 'age': 55, 'title': 'Senior VP & General Counsel', 'yearBorn': 1970, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Kristin Huguet Quayle', 'title': 'Vice President of Worldwide Communications', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Greg  Joswiak', 'title': 'Senior Vice President of Worldwide Marketing', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}], 'auditRisk': 2, 'boardRisk': 1, 'compensationRisk': 7, 'shareHolderRightsRisk': 1, 'overallRisk': 1, 'governanceEpochDate': 1785542400, 'compensationAsOfEpochDate': 1767139200, 'irWebsite': 'http://investor.apple.com/', 'executiveTeam': [], 'maxAge': 86400, 'priceHint': 2, 'previousClose': 314.58, 'open': 317.088, 'dayLow': 315.4504, 'dayHigh': 322.37, 'regularMarketPreviousClose': 314.58, 'regularMarketOpen': 317.088, 'regularMarketDayLow': 315.4504, 'regularMarketDayHigh': 322.37, 'dividendRate': 1.08, 'dividendYield': 0.34, 'exDividendDate': 1786320000, 'payoutRatio': 0.1204, 'fiveYearAvgDividendYield': 0.5, 'beta': 1.086, 'trailingPE': 36.083523, 'forwardPE': 33.516766, 'volume': 38500185, 'regularMarketVolume': 38500185, 'averageVolume': 54939019, 'averageVolume10days': 39553230, 'averageDailyVolume10Day': 39553230, 'bid': 318.02, 'ask': 324.98, 'bidSize': 3, 'askSize': 4, 'marketCap': 4665759498240, 'nonDilutedMarketCap': 4591037144400, 'fiftyTwoWeekLow': 225.95, 'fiftyTwoWeekHigh': 344.57, 'allTimeHigh': 344.57, 'allTimeLow': 0.049107, 'fulldayPrice': 319.9, 'fulldayChange': 5.12003, 'fulldayChangePercent': 1.62758, 'priceToSalesTrailing12Months': 9.994708, 'fiftyDayAverage': 312.0, 'twoHundredDayAverage': 282.60214, 'trailingAnnualDividendRate': 1.05, 'trailingAnnualDividendYield': 0.0033377837, 'currency': 'USD', 'tradeable': False, 'enterpriseValue': 4687704096768, 'profitMargins': 0.27618998, 'floatShares': 14569223952, 'sharesOutstanding': 14594180000, 'sharesShort': 116327753, 'sharesShortPriorMonth': 146547784, 'sharesShortPreviousMonthDate': 1784073600, 'dateShortInterest': 1786665600, 'sharesPercentSharesOut': 0.008, 'heldPercentInsiders': 0.01648, 'heldPercentInstitutions': 0.66398, 'shortRatio': 2.19, 'shortPercentOfFloat': 0.008, 'impliedSharesOutstanding': 14594180000, 'bookValue': 7.36, 'priceToBook': 43.4375, 'lastFiscalYearEnd': 1758931200, 'nextFiscalYearEnd': 1790467200, 'mostRecentQuarter': 1782518400, 'earningsQuarterlyGrowth': 0.271, 'netIncomeToCommon': 128929996800, 'trailingEps': 8.86, 'forwardEps': 9.53851, 'pegRatio': 2.5, 'lastSplitFactor': '4:1', 'lastSplitDate': 1598832000, 'enterpriseToRevenue': 10.042, 'enterpriseToEbitda': 27.91, '52WeekChange': 0.3916942, 'SandP52WeekChange': 0.20204377, 'lastDividendValue': 0.27, 'lastDividendDate': 1786320000, 'quoteType': 'EQUITY', 'currentPrice': 319.7, 'targetHighPrice': 400.0, 'targetLowPrice': 215.0, 'targetMeanPrice': 324.45282, 'targetMedianPrice': 335.0, 'recommendationMean': 2.18182, 'recommendationKey': 'buy', 'numberOfAnalystOpinions': 39, 'totalCash': 62399000576, 'totalCashPerShare': 4.276, 'ebitda': 167959003136, 'totalDebt': 84343996416, 'quickRatio': 0.812, 'currentRatio': 1.003, 'totalRevenue': 466822987776, 'debtToEquity': 78.445, 'revenuePerShare': 31.707, 'returnOnAssets': 0.27082002, 'returnOnEquity': 1.4875101, 'grossProfits': 227123003392, 'freeCashflow': 107721875456, 'operatingCashflow': 146723995648, 'earningsGrowth': 0.287, 'revenueGrowth': 0.164, 'grossMargins': 0.48653, 'ebitdaMargins': 0.35979, 'operatingMargins': 0.32623002, 'financialCurrency': 'USD', 'symbol': 'AAPL', 'language': 'en-US', 'region': 'US', 'typeDisp': 'Equity', 'quoteSourceName': 'Nasdaq Real Time Price', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'corporateActions': [], 'postMarketTime': 1787961599, 'regularMarketTime': 1787947201, 'exchange': 'NMS', 'messageBoardId': 'finmb_24937', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'gmtOffSetMilliseconds': -14400000, 'market': 'us_market', 'esgPopulated': False, 'regularMarketChangePercent': 1.62758, 'regularMarketPrice': 319.7, 'isEarningsDateEstimate': False, 'epsTrailingTwelveMonths': 8.86, 'epsForward': 9.53851, 'epsCurrentYear': 8.82452, 'priceEpsCurrentYear': 36.2286, 'fiftyDayAverageChange': 7.700012, 'fiftyDayAverageChangePercent': 0.024679527, 'twoHundredDayAverageChange': 37.09787, 'twoHundredDayAverageChangePercent': 0.13127244, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '2.2 - Buy', 'cryptoTradeable': False, 'hasPrePostMarketData': True, 'firstTradeDateMilliseconds': 345479400000, 'postMarketChangePercent': 0.06255292, 'postMarketPrice': 319.9, 'postMarketChange': 0.19998169, 'regularMarketChange': 5.12003, 'regularMarketDayRange': '315.4504 - 322.37', 'fullExchangeName': 'NasdaqGS', 'averageDailyVolume3Month': 54939019, 'fiftyTwoWeekLowChange': 93.750015, 'fiftyTwoWeekLowChangePercent': 0.41491488, 'fiftyTwoWeekRange': '225.95 - 344.57', 'fiftyTwoWeekHighChange': -24.869995, 'fiftyTwoWeekHighChangePercent': -0.0721769, 'fiftyTwoWeekChangePercent': 39.16942, 'dividendDate': 1786579200, 'earningsTimestamp': 1785441600, 'earningsTimestampStart': 1793304000, 'earningsTimestampEnd': 1793304000, 'earningsCallTimestampStart': 1785441600, 'earningsCallTimestampEnd': 1785441600, 'longName': 'Apple Inc.', 'marketState': 'CLOSED', 'shortName': 'Apple Inc.', 'displayName': 'Apple', 'trailingPegRatio': 2.5365}

In [5]:
from gpt_functions import get_yf_stock_history, get_yf_stock_recommendations

get_yf_stock_history('AAPL', '5d')
print('----')
get_yf_stock_recommendations('AAPL')

ImportError: cannot import name 'get_yf_stock_history' from 'gpt_functions' (c:\Users\user\Documents\GitHub\STUDY\chaewony\ch07\gpt_functions.py)